# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99d2dc025976c6c1f2694d3e5de5a145b7ac3bc8e3bb27eb288f6fba24651496b8b3d9566aad1b1fee285f1c5bb61586c905da8e974f21554bfa54378cf0250c

test:
  secret_key_base: 1ae509375d6f4ab66c787e12a9263a2829982a6b934148ac644568f88399f2bd5d5a7f12900f34cac867e1ca05bc338795eb1bd7c573c580f4cdf860a7b8dda8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
